import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#003b5a",
          container: "#1a5276",
          fixed: "#cbe6ff",
          "fixed-dim": "#9bccf6",
        },
        secondary: {
          DEFAULT: "#9a4600",
          container: "#fe8028",
          fixed: "#ffdbc9",
          "fixed-dim": "#ffb68d",
          saffron: "#f47920",
        },
        tertiary: {
          DEFAULT: "#00410c",
          container: "#005b14",
          fixed: "#a3f69c",
          "fixed-dim": "#88d982",
          emerald: "#2e7d32",
        },
        surface: {
          DEFAULT: "#f8f9ff",
          bright: "#f8f9ff",
          dim: "#cbdbf5",
          container: "#e5eeff",
          "container-low": "#eff4ff",
          "container-high": "#dce9ff",
          "container-highest": "#d3e4fe",
          "container-lowest": "#ffffff",
          variant: "#d3e4fe",
          tint: "#2f6388",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#94c5ee",
        "on-primary-fixed": "#001e30",
        "on-primary-fixed-variant": "#0e4b6e",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#612900",
        "on-secondary-fixed": "#321200",
        "on-secondary-fixed-variant": "#763300",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#81d27c",
        "on-tertiary-fixed": "#002204",
        "on-tertiary-fixed-variant": "#005312",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#41474e",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#9bccf6",
        outline: "#72787f",
        "outline-variant": "#c1c7cf",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["'Public Sans'", "system-ui", "-apple-system", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        gov: "0 1px 3px 0 rgba(11, 28, 48, 0.06), 0 1px 2px -1px rgba(11, 28, 48, 0.04)",
        "gov-md": "0 4px 12px -2px rgba(11, 28, 48, 0.08), 0 2px 6px -1px rgba(11, 28, 48, 0.04)",
        "gov-lg": "0 12px 28px -6px rgba(11, 28, 48, 0.12), 0 4px 12px -2px rgba(11, 28, 48, 0.06)",
      },
    },
  },
  plugins: [],
};
export default config;
